/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "todo.index": [],
    "todo.create": [],
    "todo.store": [],
    "todo.show": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "todo.edit": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "todo.update": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "todo.destroy": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
